// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// home.js
export const FETCH_HOME_SUCCESS = 'FETCH_HOME_SUCCESS'
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS'
export const FETCH_AGREEMENT_SUCCESS = 'FETCH_AGREEMENT_SUCCESS'
export const FETCH_PRIVACY_SUCCESS = 'FETCH_PRIVACY_SUCCESS'

// location.js
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS'
export const FETCH_AREAS_SUCCESS = 'FETCH_AREAS_SUCCESS'
export const UPDATE_USER_LOCATION_SUCCESS = 'UPDATE_USER_LOCATION_SUCCESS'

// place.js
export const FETCH_PLACE_SUCCESS = 'FETCH_PLACE_SUCCESS'
export const TOGGLE_FAV_SUCCESS = 'TOGGLE_FAV_SUCCESS'
export const UPDATE_PLACE_SUCCESS = 'UPDATE_PLACE_SUCCESS'
export const FETCH_CATEGORY_PLACES_SUCCESS = 'FETCH_CATEGORY_PLACES_SUCCESS'
export const TOGGLE_FAV_CATEGORY_PLACE_SUCCESS = 'TOGGLE_FAV_CATEGORY_PLACE_SUCCESS'
export const FETCH_FAVORITE_PLACES_SUCCESS = 'FETCH_FAVORITE_PLACES_SUCCESS'
export const TOGGLE_FAV_FAVORITE_PLACE_SUCCESS = 'TOGGLE_FAV_FAVORITE_PLACE_SUCCESS'
export const ADD_PLACE_SERVICE_SUCCESS = 'ADD_PLACE_SERVICE_SUCCESS'
export const ADD_PLACE_PRODUCT_SUCCESS = 'ADD_PLACE_PRODUCT_SUCCESS'
export const ADD_PLACE_OFFER_SUCCESS = 'ADD_PLACE_OFFER_SUCCESS'

// general.js
export const CHANGE_WAIT = 'CHANGE_WAIT'
export const CHANGE_ROUTE_NAME = 'CHANGE_ROUTE_NAME'

// chat.js
export const FETCH_CONVERSATIONS_SUCCESS = 'FETCH_CONVERSATIONS_SUCCESS'